/**
 * Reads chapters.json + all level JSONs → outputs src/levels.js
 * Run with: bun run build:levels
 */
import { readFileSync, writeFileSync, existsSync } from "fs";
import { join } from "path";

const ROOT = join(import.meta.dir, "..");
const LEVELS_DIR = join(ROOT, "levels");
const SRC_DIR = join(ROOT, "src");

// Read chapters.json
const chapters: { name: string; levels: string[] }[] = JSON.parse(
  readFileSync(join(LEVELS_DIR, "chapters.json"), "utf-8")
);

// Read all level files in chapter order
const allLevels: any[] = [];
const chapterDefs: { name: string; levels: number[] }[] = [];

let globalIdx = 1;
for (const chapter of chapters) {
  const levelIndices: number[] = [];
  for (const relPath of chapter.levels) {
    const fullPath = join(LEVELS_DIR, relPath);
    if (!existsSync(fullPath)) {
      console.error(`Missing level file: ${fullPath}`);
      process.exit(1);
    }
    const levelData = JSON.parse(readFileSync(fullPath, "utf-8"));

    // Strip metadata for the browser build (not needed at runtime)
    const { metadata, ...runtimeData } = levelData;
    // Also strip the id field — the game uses array index
    const { id, ...rest } = runtimeData;
    allLevels.push(rest);
    levelIndices.push(globalIdx);
    globalIdx++;
  }
  chapterDefs.push({ name: chapter.name, levels: levelIndices });
}

// Generate dist/levels.js
const output = `// levels.js — Auto-generated by build-levels.ts. DO NOT EDIT MANUALLY.
// grid cell values: 0=empty, 1=obstacle(tree), 'S'=start, 'E'=end, 'G'=gas station

window.CHAPTERS = ${JSON.stringify(chapterDefs, null, 2)};

window.LEVELS = ${JSON.stringify(allLevels, null, 2)};
`;

writeFileSync(join(SRC_DIR, "levels.js"), output);
console.log(`Wrote src/levels.js (${allLevels.length} levels, ${chapterDefs.length} chapters)`);

console.log("Build complete!");
